---
language: ruby
cache: bundler
sudo: false
rvm: 2.2.3
env:
  global:
  - GIT_COMMITTER_NAME: fukayatsu
  - GIT_COMMITTER_EMAIL: fukayatsu@gmail.com
  - GIT_AUTHOR_NAME: fukayatsu
  - GIT_AUTHOR_EMAIL: fukayatsu@gmail.com
before_script:
  - git clone --quiet https://github.com/fukayatsu/blog.git build
  - pushd build
  - git checkout -b gh-pages
  - popd
script:
  - bundle exec middleman build
after_success:
  - cd build
  - git add -A
  - git status
  - git commit -m 'Updated by Travis CI'
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && git push --quiet https://$GH_TOKEN@github.com/fukayatsu/blog.git gh-pages -f 2> /dev/null'
branches:
  only:
    - master
